apiVersion: v1
kind: Pod
metadata:
  name: aspnetapp
  labels:
    app: aspnetapp
spec:
  containers:
  - name: aspnetapp
    image: aspnetapp
    imagePullPolicy: Never
    ports:
      - name: http
        protocol: TCP
        containerPort: 80
      - name: https
        protocol: TCP
        containerPort: 443
    volumeMounts:
      - name: aspnetapp-volume
        mountPath: /app/aspnetapp.conf
        subPath: aspnetapp.conf
      # - name: aspnetapp-volume2
      #   mountPath: /app/aspnetapp2.conf
      #   subPath: aspnetapp2.conf
    env:
      - name: TEST_ENV_VAR
        value: test_env_var_value
      - name: TEST_ENV_VAR_FROM_CONFIG-MAP2
        valueFrom:
          configMapKeyRef:
            name: aspnetapp-config2
            key: TEST_ENV_VAR_FROM_CONFIG-MAP2
    envFrom:
      - configMapRef:
          name: aspnetapp-config
  volumes:
    - name: aspnetapp-volume
      configMap:
        name: aspnetapp-config3
    # - name: aspnetapp-volume2
    #   hostPath:
    #     path: aspnetapp2.conf
